# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160222_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('name', models.CharField(default='', max_length=140, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
