# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sku',
            field=models.SlugField(default=datetime.datetime(2016, 3, 17, 21, 19, 16, 155354, tzinfo=utc), editable=False, unique=True, verbose_name='SKU'),
            preserve_default=False,
        ),
    ]
