# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160318_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN', 'In stock'), ('OUT', 'Out of stock')], default='OUT', editable=False, max_length=3, verbose_name='Status'),
        ),
    ]
