# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20160318_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 18, 2, 15, 23, 599569, tzinfo=utc), verbose_name='Date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 3, 18, 2, 15, 33, 312088, tzinfo=utc), verbose_name='Date updated'),
            preserve_default=False,
        ),
    ]
