# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20160318_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('title', models.CharField(default='', max_length=140, verbose_name='Title')),
                ('text', models.TextField(blank=True, default='', verbose_name='Text')),
                ('publish', models.BooleanField(default=False, verbose_name='Publish')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date added')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date updated')),
            ],
            options={
                'ordering': ['order', 'date', 'slug'],
                'verbose_name_plural': 'press items',
                'verbose_name': 'press',
            },
        ),
        migrations.CreateModel(
            name='PressImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(default='', max_length=140, verbose_name='Name')),
                ('image', models.ImageField(upload_to=store.models.upload_image_to, verbose_name='Image')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date added')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date updated')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Press')),
            ],
            options={
                'ordering': ['order', 'date'],
                'verbose_name_plural': 'images',
                'verbose_name': 'image',
            },
        ),
        migrations.CreateModel(
            name='VideoPress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(default='', max_length=140, verbose_name='Name')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date added')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date updated')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Press')),
            ],
            options={
                'ordering': ['order', 'date'],
                'verbose_name_plural': 'video',
                'verbose_name': 'video',
            },
        ),
    ]
