# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_press_pressimage_videopress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('name', models.CharField(default='', max_length=140, verbose_name='Name')),
                ('adress', models.CharField(default='', max_length=500, verbose_name='Adress')),
                ('mail', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='', max_length=140, verbose_name='Phone')),
                ('notes', models.CharField(default='', max_length=500, verbose_name='Notes')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date added')),
            ],
            options={
                'verbose_name_plural': 'Stores',
                'ordering': ['order', 'date', 'slug'],
                'verbose_name': 'Store',
            },
        ),
    ]
