# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
    ]
