# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20160329_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(default='', max_length=140, verbose_name='Name')),
                ('image', models.ImageField(upload_to=store.models.upload_image_to, verbose_name='Image')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date added')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'VOV', 'verbose_name_plural': 'VOV'},
        ),
        migrations.RenameField(
            model_name='store',
            old_name='description',
            new_name='big_description',
        ),
        migrations.AddField(
            model_name='store',
            name='facebook',
            field=models.URLField(blank=True, default='', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram',
            field=models.URLField(blank=True, default='', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='store',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='store',
            name='small_description',
            field=models.CharField(default='', max_length=140, verbose_name='Small description'),
        ),
        migrations.AddField(
            model_name='store',
            name='twitter',
            field=models.URLField(blank=True, default='', verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='storeimage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
