# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 03:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20160329_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='big_description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Description'),
        ),
    ]
