# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
    ]
