# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_category_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='date_article',
            field=models.DateField(default=datetime.datetime(2016, 5, 20, 22, 59, 46, 441789, tzinfo=utc), verbose_name='Date article'),
            preserve_default=False,
        ),
    ]
