# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_press_date_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(default='', max_length=140, verbose_name='Name')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date added')),
                ('updated', models.DateField(auto_now=True, verbose_name='Date updated')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductVariant')),
            ],
            options={
                'ordering': ['order', 'date'],
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
        ),
        migrations.AlterModelOptions(
            name='press',
            options={'ordering': ['order', 'date_article', 'slug'], 'verbose_name': 'press', 'verbose_name_plural': 'press items'},
        ),
    ]
