# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20161101_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='store',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Twitter'),
        ),
    ]
