# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20170320_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default=1, upload_to=store.models.upload_image_to, verbose_name='Preview Image'),
            preserve_default=False,
        ),
    ]
