# Generated by Django 2.1 on 2018-11-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20170914_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external',
            field=models.URLField(blank=True, null=True, verbose_name='External Link'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingAdress',
            field=models.ForeignKey(limit_choices_to={'type': 'BIL'}, on_delete=django.db.models.deletion.CASCADE, related_name='billingAdress', to='store.Adress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingAdress',
            field=models.ForeignKey(limit_choices_to={'type': 'SHI'}, on_delete=django.db.models.deletion.CASCADE, related_name='shippingAdress', to='store.Adress'),
        ),
    ]
