# Generated by Django 2.1 on 2018-12-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20181107_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
    ]
